// packages/vue/src/button.tsx
import { defineComponent } from 'vue';
import { style, styleInject } from '@img-uploader/core';

styleInject(style);
export default defineComponent({
  name: 'CButton',
  inheritAttrs: false,
  props: {
    onClick: Function
  },
  setup(props, { slots, attrs }) {
    return () => {
      const eventProps = { ...props, ...attrs };
      return (
        <button {...(eventProps as any)} class='button'>
          {slots.default?.()}
        </button>
      );
    };
  }
});

// packages/react/src/button.tsx
import { style, styleInject } from '@img-uploader/core'
import React, { FC, ReactNode } from 'react'

styleInject(style)

export interface ButtonProps {
  type?: 'primary' | 'secondary' | 'error'
  children?: ReactNode
  onClick: () => void
}

const CButton: FC<ButtonProps> = ({ type, onClick, children }) => {
  return (
    <button type='button' className={`Button Button-${type}`} onClick={onClick}>
      {children}
    </button>
  )
}

export default CButton
